BST_DESTINATIONS = [
    "California College of the Arts",
    "Columbia University",
    "Durham University",
    "Imperial College London",
    "King's College London",
    "Kingston University London",
    "Kyushu University",
    "Leiden University",
    "Liverpool Hope University",
    "London School of Economics",
    "Maastricht University",
    "Michigan State University",
    "Nottingham Trent University",
    "Ritsumeikan University",
    "Smith College",
    "The University of British Columbia",
    "The University of Sheffield",
    "University College London",
    "United International Business Schools",
    "University of Birmingham",
    "University of Oxford",
    "University of Southampton",
    "University of the Arts London",
    "University of Toronto",
    "University of Toronto Scarborough",
    "University of Waterloo",
    "University of Westminster",
    "Utrecht University",
]
LFIT_DESTINATIONS = [
    # France
    "Universités de Paris La Sorbonne",
    "Université d'Assas -Paris-II",
    "Université René Descartes -Paris-V",
    "University of Global Business",
    "Universités de Technologie",
    "Institut d'Administration des Entreprises",
    "Sciences-Po Paris",
    "CPES Paris Sciences & Lettres + Lycée Henri-IV",
    "Bachelor of the Ecole Polytechnique",
    "Penninghen Institute of Art and Design",
    "Olivier de Serres",
    "Ecole du Louvre",
    "Vatel International Hospitality Management School",
    "Ferrandi International Hospitality Management School",
    "ESSEC School of Management",
    "ESCP Europe",
    "EDHEC Business School",
    "EM Lyon",
    "IESEG School of Management",
    "ENSA School of Architecture",
    "INSA Lyon",
    "ISIPCA Paris",
    "ISTR Lyon",
    # England
    "Cambridge University",
    "University College of London",
    "Warwick University",
    "King's College London",
    "London School of Economics",
    "Imperial College",
    # Netherlands
    "Hospitality Management School of The Hague",
    "University of Amsterdam",
    "University of Gröningen",
    "University of Rotterdam",
    # Switzerland
    "Ecole Polytechnique Fédérale de Lausanne",
    "Ecole hôtelière de Lausanne",
    "Eidgenössische Technische Hochschule Zürich",
    # Belgium
    "Université de Louvain",
    "Université Libre",
    "University of Mechelen",
    # Italy
    "Università Cattolica del Sacro Cuore Medicine and Surgery program",
    "LUISS Guido Carli",
    "Bocconi School of Management",
    # Germany
    "HTW Berlin",
    "München Universität",
    # Japan
    "Waseda University",
    "Keio University",
    "Temple University",
    "Musashino Art University",
    # Canada
    "Mc Gill University",
    "Concordia University",
    "Université de Montréal",
    "University of British Columbia",
    "University of Toronto",
    # United States of America
    "University of California",
    "Middlebury College",
]
